In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/

In [ ]:
import pandas as pd
df=pd.read_csv("/content/drive/My Drive/previous_application.csv")
df.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
mondays=df[df["WEEKDAY_APPR_PROCESS_START"]=="MONDAY"]

In [ ]:
non_null_drawing=mondays["DAYS_FIRST_DRAWING"].fillna(0)

In [ ]:
non_null_drawing

In [ ]:
mean_monday_drawing,std_monday_drawing=non_null_drawing.mean(),non_null_drawing.std()

In [ ]:
mean_monday_drawing,std_monday_drawing

(192543.06395011774, 182391.00962884806)

In [ ]:
mean_thresh=200000
std_thresh=180000

In [ ]:
import smtplib
server = smtplib.SMTP('smtp.gmail.com',587)
server.starttls()


password=input("Enter Password:")

server.login('<Sender Email ID>',password)

if mean_monday_drawing<mean_thresh:
  msg="Notification! Mean Drawing on Monday below threshold. Value = {}".format(mean_monday_drawing)
  server.sendmail('<Sender Email ID>','<Receiver email ID>',msg)

if std_monday_drawing<std_thresh:
  msg="Notification! Std. Drawing on Monday below threshold. Value = {}".format(std_monday_drawing)
  server.sendmail('<Sender Email ID>','<Receiver email ID>',msg)

print("Done")